# Generated by Django 4.2.18 on 2025-02-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pick",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[("AWAY", "AWAY"), ("HOME", "HOME")],
                max_length=10,
                null=True,
            ),
        ),
    ]
